baseURL = "https://igledaniel.github.io/web-test2/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'pehtheme-hugo'

[params]
[params.author]
name = 'Daniel'
bio = 'A passionate writer exploring the wonders of space and astronomy'
avatar = 'images/default-placeholder.png'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"